# Reflexiones finales

La comparación entre las democracias Chilena y Sueca nos indica que, aunque ambas son democracias efectivas poseen algunas diferencias de la primera respecto a la segunda. Por un lado, la democracia de Chile se ve afectada por su incapacidad de garantizar algunos derechos propios de los ciudadanos como el acceso a la justicia o algunos derechos sociales. Por otro lado, la democracia Chilena posee una menor estabilidad histórica, siendo esta más bien reciente y estando garantizada solo hace 30 años en este país.

La diferencia de la calidad de la democracia de ambos países posee cierto correlato en la opinión pública de estos países. De este modo, en Chile existe una menor confianza en las instituciones judiciales, lo cual es consistente con la peor evaluación internacional de la garantía del derecho a justicia. Curiosamente, existen grandes diferencias en la satisfacción con la democracia de cada país, aunque ambas comparten buenas cualidades democráticas según el índice de la democracia, como los chequeos gubernamentales, la representatividad y la imparcialidad en la administración.  

En este contexto institucional y de opinión publica resultan interesantes las diferencias en la vivencia democrática de los jóvenes de ambos países.

Aunque la diferencia de la calidad de la democracia parece expresarse en diferencias en la satisfacción de esta por parte de los jóvenes de ambos países, no parece tener un correlato con posibles diferencias en los valores democráticos de estos jóvenes ni en su participación. Más bien, se observa que los jóvenes de ambos países poseen una valoración similar de la democracia y de sus valores, a la vez que poseen distintos patrones de participación. En el caso sueco predomina un patrón de participación juvenil muy directo, en consejos, reuniones y voluntariados estudiantiles, mientras que en el caso de chile se observa una alta participación contenciosa en distintos tipos de protesta. 

Además, en la muestra analizadas se puede apreciar que los jóvenes chilenos participan más frecuentemente en conversaciones sobre política, sociedad o medio ambiente. La socialización política familiar y entre pares es fundamental para comprender la ciudadanía juvenil. En vista de la información recopilada, se puede pensar que las distintas deficiencias de la democracia en torno a la participación y los derechos fomentan una menor confianza y satisfacción con la democracia tanto en adultos como en jóvenes, lo cual podría estar relacionado con la alta participación de los jóvenes Chilenos en protestas.

Para futuros estudios sería muy valioso comprender que se asocia con la los diferentes tipos de participación de cada país. Evidencia anterior sugiere tanto la socialización familiar, la opinión de los padres sobre la democracia y la propia confianza en las instituciones de los jóvenes podrían influir su participación en protestas. No obstante ¿esta asociación ocurre del mismo modo en ambos contextos? 




