---
title: '<span style="color: #D88712;"> Chile y Suecia </span>: Una comparación de los sistemas politicos y la ciudadania juvenil'
subtitle: "Fondecyt n°1181239: Socialización política y experiencia escolar: el rol de la familia y la escuela"
author: "Francisco Javier Meneses Rivas"
date: "Santiago de Chile, año 2022" # o para fecha actual: "`r Sys.Date()`"
institution: "Universidad Diego Portales, Universidad Católica y Universidad de Chile"
#degree: "Tesis para optar al grado de Magister en Ciencias Sociales"
#advisor: "Profesor guía \n Juan Carlos Castillo"
biblio-style: apalike
link-citations: yes
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
fontsize: 12pt
lof: True
lot: True
---



# Resumen {-}

Se expone una comparación entre las democracias de Chile y de Suecia para intentar comprender las diferencias encontradas en las practicas actitudes y creencias ciudadanas de jóvenes adolescentes de ambos países. La primera sección del documento describe ambos sistemas políticos, para luego compararlos a la luz de diversos indicadores de democracia. La segunda sección busca dar cuenta del clima político y democrático mediante la exposición de la opinión pública de los adultos de ambos países. La tercera sección destaca las diferencias en actitudes ciudadanas encontradas en ambos países en dos muestras independientes, para corroborar dichas diferencias a la luz de los datos de la encuesta internacional ICCS. 

__Palabras clave__: Ciudadania, sistemas politicos, democracia, Suecia, Chile

# Agradecimientos {-}

